### ISSUE TITLE
just print one time 

### ISSUE THREAD

**Issue by mahmadinia** [mahmadinia/python_help#1]
hey man
when i reed the line in the file .txt , just i like to see one time if i have the same line , for example for this : 
KDMA
KDMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KDMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA
KMMA

, just show me
 KDMA
KMMA

with out itteration , 

thanks man could you please  send me soon .

**Comment by arnagaram** [comment]
With out reading each line its not possible to get the unique terms in the file. The following code snippet should help.

``` python
fileLines=open('file.txt','r') #opens file with name of "file.txt" in read mode

uniqueTerms=[] #consists of unique terms in the file we read
for line in fileLines: # parsing through each line of the file 
  wordToDisplayInLine=line    #write the code for placing a word in the line, as you may want to make changes to extract a word from the line rather than whole line of the file
  if wordToDisplayInLine not in uniqueTerms:  #condition to check if the word already in the array or not
       unqiueTerms.append(wordToDisplayInLine)  #adding the unique word in to the array
print(uniqueTerms) #prints the unique terms in the file




```

**Comment by mahmadinia** [comment]
Great help man , thanks
